version: '2.2'

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.license.self_generated.type=basic 
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true 
      - xpack.security.http.ssl.key=/usr/share/elasticsearch/config/certificates/es01/es01.key
      - xpack.security.http.ssl.certificate_authorities=/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - xpack.security.http.ssl.certificate=/usr/share/elasticsearch/config/certificates/es01/es01.crt
      - xpack.security.transport.ssl.enabled=true 
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - xpack.security.transport.ssl.certificate=/usr/share/elasticsearch/config/certificates/es01/es01.crt
      - xpack.security.transport.ssl.key=/usr/share/elasticsearch/config/certificates/es01/es01.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
      - c:\mobilesiem\certs\ca\ca.crt:/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - c:\mobilesiem\certs\es01\es01.crt:/usr/share/elasticsearch/config/certificates/es01/es01.crt
      - c:\mobilesiem\certs\es01\es01.key:/usr/share/elasticsearch/config/certificates/es01/es01.key
      - c:\mobilesiem\certs\kib01\kib01.crt:/usr/share/elasticsearch/config/certificates/kib01/kib01.crt
      - c:\mobilesiem\certs\kib01\kib01.key:/usr/share/elasticsearch/config/certificates/kib01/kib01.key
    ports:
      - 9200:9200
    networks:
      - elastic

    healthcheck:
      test: curl --cacert $CERTS_DIR/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kib01:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kib01
    depends_on: {"es01": {"condition": "service_healthy"}}
    ports:
      - 5601:5601
    environment:
      SERVERNAME: localhost
      ELASTICSEARCH_URL: https://es01:9200
      ELASTICSEARCH_HOSTS: https://es01:9200
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: rHVdsK7gqCedZUYL6Qh6
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: /usr/share/elasticsearch/config/certificates/ca/ca.crt
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY: /usr/share/elasticsearch/config/certificates/kib01/kib01.key
      SERVER_SSL_CERTIFICATE: /usr/share/elasticsearch/config/certificates/kib01/kib01.crt
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 'fhjskloppd678ehkdfdlliverpoolfcr'
      NODE_OPTIONS: "--max-old-space-size=4096"
    volumes:
      - c:\mobilesiem\certs\ca\ca.crt:/usr/share/elasticsearch/config/certificates/ca/ca.crt
      - c:\mobilesiem\certs\es01\es01.crt:/usr/share/elasticsearch/config/certificates/es01/es01.crt
      - c:\mobilesiem\certs\es01\es01.key:/usr/share/elasticsearch/config/certificates/es01/es01.key
      - c:\mobilesiem\certs\kib01\kib01.crt:/usr/share/elasticsearch/config/certificates/kib01/kib01.crt
      - c:\mobilesiem\certs\kib01\kib01.key:/usr/share/elasticsearch/config/certificates/kib01/kib01.key
    networks:
      - elastic    

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.6.2
#    container_name: logstash
#    links:
#    - es01
#    ports:
#      - 5044:5044
#      - 6050:6050
#      - 6051:6051
#      - 6052:6052
#      - 6053:6053
#    environment:
#      ELASTICSEARCH_URL: https://es01:9200
#      ELASTICSEARCH_HOSTS: https://es01:9200
#    volumes:
#      - C:\MobileSIEM\logstash\jvm.options:/usr/share/logstash/config/jvm.options:ro
#      - C:\MobileSIEM\logstash\log4jz.properties:/usr/share/logstash/config/log4jz.properties:ro
#      - C:\MobileSIEM\logstash\logstash.yml:/usr/share/logstash/config/logstash.yml:ro
#      - C:\MobileSIEM\logstash\logstash-ossec-template.json:/logstash-ossec-template.json:ro
#      - C:\MobileSIEM\logstash\logstash-template.json:/logstash-template.json:ro
#      - C:\MobileSIEM\logstash\beats-template.json:/beats-template.json:ro
#      - C:\MobileSIEM\logstash\Stable\:/usr/share/logstash/pipeline/:ro
#      - C:\MobileSIEM\logstash\Stable\:/usr/share/logstash/conf.d.available/:ro
#      - C:\MobileSIEM\logstash\rules:/etc/nsm/rules:ro
#      - C:\MobileSIEM\logstash\dictionaries\:/lib/dictionaries:ro
#      - C:\MobileSIEM\logstash\:/var/log/logstash
#      - C:\MobileSIEM\logstash\securityonion\:/var/log/nsm/securityonion:ro
#      - c:\mobilesiem\testing\certs\ca\ca.crt:/usr/share/elasticsearch/config/certificates/ca/ca.crt
#    depends_on: {"es01": {"condition": "service_healthy"}}
#    networks:
#      - elastic
#
  wazuh:
    image: wazuh/wazuh:3.13.1_7.8.0
    container_name: wazuh
    restart: always     
    ports:
      - 1514:1514/udp
      - 1515:1515
      - 514:514/udp
      - 55000:55000 
    networks:
      - elastic
    volumes:
      - c:\mobilesiem\certs\wazuh\wazuh.crt:/etc/filebeat/certs/wazuh.crt
      - c:\mobilesiem\certs\wazuh\wazuh.key:/etc/filebeat/certs/wazuh.key
      - c:\mobilesiem\wazuh\filebeat.yml:/etc/filebeat/filebeat.yml
      - c:\mobilesiem\certs\ca\ca.crt:/etc/filebeat/certs/ca/ca.crt 
      - c:\mobilesiem\certs\ca\ca.crt:/configuration/ssl/ca.crt 
      - c:\mobilesiem\certs\wazuh\wazuh.crt:/configuration/ssl/wazuh.crt
      - c:\mobilesiem\certs\wazuh\wazuh.key:/configuration/ssl/wazuh.key 

volumes:
  data01:
    driver: local

networks:
  host:
    driver: host 
  elastic:
    driver: bridge
